export { Hero } from './Hero/Hero'
export { Welcome } from './Welcome/Welcome'
export { Oferts } from './Oferts/Oferts'
export { Testimonial } from './Testimonial/Testimonial'
export { Blog } from './Blog/Blog'
export { Contact } from './Contact/Contact'